import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    height: "100%",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eeddee",
  },
  titleText: {
    fontSize: 24,
    fontWeight: "bold",
    flex: 1,
    textAlign: "center",
  },
  textInput: {
    height: 40,
    width: "90%",
    borderColor: "gray",
    borderWidth: 1,
    marginTop: 8,
    padding: 8,
  },
  btn: {
    marginVertical: 8,
    marginHorizontal: 16,
    height: 40,
    padding: 8,
    backgroundColor: "#FFA044",
    color: "black",
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    width: "90%",
  },
  itemContainer: {
    width: "100%",
    borderRadius: 8,
    borderColor: "black",
    backgroundColor: "#FFA044",
    padding: 8,
    marginHorizontal: 8,
    alignSelf: "center",
    flexDirection: "column",
  },
  listContainer: {
    flex: 1,
    width: "100%",
    alignSelf: "center",
    padding: 16,
    gap: 16,
  },
  itemDesc: {
    padding: 10,
    fontSize: 18,
    width: '100%',
    height: "auto",
    backgroundColor: "#FFEFD5",
    justifyContent: 'center',
  },
  itemTitle: {
    // display: "flex",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    fontSize: 18,
    height: 40,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,

    width: '100%',
    padding: 10,
    backgroundColor: "transparent",
    // backgroundColor: "#FFDAB9 #FFA07A #FFEFD5 #FFE4B5",
  },
  list: {
    width: "100%",
    flex: 1,
    alignSelf: "center",
  },
  completedItem: {
    backgroundColor: "green",
  },
  pending: {
    // backgroundColor: "gray",
  },
  completedText: {
    textDecorationLine: "line-through",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    width: '90%',
    height: 'auto',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  openButton: {
    backgroundColor: "#000",
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  icon: {
    width: 44,
    height: 44,
    backgroundColor: "white",
    borderRadius: 22,
    padding: 8,
    margin: 8,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  colorPicker: {
    width: '100%',
    height: '50%', // Adjust height as needed
    marginVertical: 10,
  },
  colorPickerContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    height: '50%',
  },
  colorPickerItem: {
    width: 44,
    height: 44,
    backgroundColor: "white",
    borderRadius: 22,
    padding: 8,
    margin: 8,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  horizontalLine: {
    width: '100%',
    borderBottomColor: '#EFE4BE',
    borderBottomWidth: 1,
    marginVertical: 10,

  },
  itemIcons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    padding: 1,
    backgroundColor: "transparent",
    color: "black",
  },
  notCompleted: {
    fontSize: 18,
    color: 'blue',
    textAlign: 'center',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: {
    color: "black",
    textAlign: "center",
    fontSize: 18,
  },
  editContainer: {
    width: "60px",
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },

});
